// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus_Status int32

const (
	ResponseStatus_OK   ResponseStatus_Status = 0
	ResponseStatus_FAIL ResponseStatus_Status = 1
)

var ResponseStatus_Status_name = map[int32]string{
	0: "OK",
	1: "FAIL",
}

var ResponseStatus_Status_value = map[string]int32{
	"OK":   0,
	"FAIL": 1,
}

func (x ResponseStatus_Status) String() string {
	return proto.EnumName(ResponseStatus_Status_name, int32(x))
}

func (ResponseStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0, 0}
}

type ResponseStatus struct {
	Status               ResponseStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.ResponseStatus_Status" json:"status,omitempty"`
	Comment              string                `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetStatus() ResponseStatus_Status {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_OK
}

func (m *ResponseStatus) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type RegistrationRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationRequest) Reset()         { *m = RegistrationRequest{} }
func (m *RegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*RegistrationRequest) ProtoMessage()    {}
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationRequest.Unmarshal(m, b)
}
func (m *RegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationRequest.Marshal(b, m, deterministic)
}
func (m *RegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationRequest.Merge(m, src)
}
func (m *RegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_RegistrationRequest.Size(m)
}
func (m *RegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationRequest proto.InternalMessageInfo

func (m *RegistrationRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *RegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticationRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationRequest) Reset()         { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()    {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *AuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationRequest.Unmarshal(m, b)
}
func (m *AuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationRequest.Merge(m, src)
}
func (m *AuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticationRequest.Size(m)
}
func (m *AuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationRequest proto.InternalMessageInfo

func (m *AuthenticationRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthenticationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.ResponseStatus_Status", ResponseStatus_Status_name, ResponseStatus_Status_value)
	proto.RegisterType((*ResponseStatus)(nil), "pb.ResponseStatus")
	proto.RegisterType((*RegistrationRequest)(nil), "pb.RegistrationRequest")
	proto.RegisterType((*AuthenticationRequest)(nil), "pb.AuthenticationRequest")
	proto.RegisterType((*AuthToken)(nil), "pb.AuthToken")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0xc4, 0x51, 0x31, 0xcd, 0x13, 0x44, 0xd5, 0x03, 0x44, 0xc8, 0x54, 0x32, 0x75, 0xb2, 0x44,
	0xd9, 0xe8, 0x54, 0x06, 0x50, 0x05, 0x12, 0x92, 0x61, 0x62, 0x4b, 0x8a, 0xd5, 0x46, 0x50, 0xdb,
	0xc4, 0x2f, 0x42, 0x7c, 0x02, 0x7f, 0x8d, 0xe2, 0x24, 0x88, 0x2a, 0x6c, 0x9d, 0xfc, 0x4e, 0x7e,
	0x77, 0xe7, 0x3b, 0x03, 0x64, 0x15, 0xad, 0x85, 0x2d, 0x0d, 0x19, 0x0c, 0x6c, 0x9e, 0x7e, 0x41,
	0x24, 0x95, 0xb3, 0x46, 0x3b, 0xf5, 0x44, 0x19, 0x55, 0x0e, 0x2f, 0x81, 0x3b, 0x3f, 0xc5, 0x6c,
	0xcc, 0x26, 0xd1, 0xf4, 0x5c, 0xd8, 0x5c, 0x6c, 0xef, 0x88, 0xe6, 0x90, 0xed, 0x22, 0xc6, 0x70,
	0xb0, 0x34, 0x9b, 0x8d, 0xd2, 0x14, 0x07, 0x63, 0x36, 0x09, 0x65, 0x07, 0xd3, 0x04, 0x78, 0x2b,
	0xcb, 0x21, 0x78, 0xbc, 0x1f, 0xed, 0xe1, 0x10, 0x06, 0xb7, 0xf3, 0xc5, 0xc3, 0x88, 0xa5, 0x77,
	0x70, 0x2c, 0xd5, 0xaa, 0x70, 0x54, 0x66, 0x54, 0x18, 0x2d, 0xd5, 0x47, 0xa5, 0x1c, 0xe1, 0x09,
	0xec, 0xbf, 0x9b, 0x55, 0xa1, 0xbd, 0x7d, 0x28, 0x1b, 0x80, 0x09, 0x0c, 0x6d, 0xe6, 0xdc, 0xa7,
	0x29, 0x5f, 0x5b, 0x8f, 0x5f, 0x9c, 0x2e, 0xe0, 0x74, 0x5e, 0xd1, 0x5a, 0x69, 0x2a, 0x96, 0x3b,
	0x4a, 0x5d, 0x40, 0x58, 0x4b, 0x3d, 0x9b, 0x37, 0xa5, 0x6b, 0x3a, 0xd5, 0x43, 0x47, 0xf7, 0x60,
	0xfa, 0xcd, 0x20, 0xda, 0xb6, 0xc3, 0x19, 0x1c, 0xfe, 0x4d, 0x82, 0x67, 0x4d, 0x65, 0xbd, 0x6c,
	0x09, 0xf6, 0xbb, 0xc4, 0xeb, 0x9e, 0x9c, 0x6f, 0xfc, 0xdf, 0x44, 0xc9, 0x51, 0x77, 0xe5, 0x5f,
	0x78, 0xc3, 0x5f, 0x06, 0x62, 0x66, 0xf3, 0x9c, 0xfb, 0x0f, 0xbd, 0xfa, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xd5, 0x00, 0xcd, 0x31, 0xde, 0x01, 0x00, 0x00,
}
