version: "3.9"

services:
  gophkeeper:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: "qwerty1234"
    depends_on:
      - postgres
  
  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "qwerty1234"
    ports:
      - "5436:5432"
