version: "3.9"

services:
  gophkeeper:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: "qwerty1234"
    depends_on:
      - postgres
  
  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "qwerty1234"
    ports:
      - "5436:5432"
  
  redis:
    restart: always
    image: redis:latest
    command: redis-server --bind 0.0.0.0 --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports: 
    - "6379:6379"

